- admin/pnpm-lock.yaml
- admin/strapi/package.json
> Revert "chore(deps): update dependency @strapi/typescript-utils to v4.12.0"

- .github/workflows/ci.yaml
- packages/@1/infra/trpc/package.json
- packages/@1/infra/trpc/tsconfig.json
- packages/@1/modules/auth/api/tsconfig.json
- packages/@1/modules/auth/emails/emails/magic-link.tsx
- packages/@1/modules/auth/emails/index.ts
- packages/@1/modules/auth/emails/package.json
- packages/@1/modules/auth/emails/src/index.ts
- packages/@1/modules/auth/emails/tsconfig.json
- packages/@1/modules/profile/api/.gitignore
- packages/@1/modules/profile/api/tsconfig.json
- packages/@1/modules/profile/domain/.gitignore
- packages/@1/modules/profile/domain/tsconfig.json
- packages/@1/modules/trpc/.gitignore
- packages/@1/modules/trpc/package.json
- packages/@1/modules/trpc/tsconfig.json
- pnpm-lock.yaml
> feat(auth): new email build system

- apps/www/package.json
- packages/@1/ui/react/package.json
- packages/__legacy__/ui/package.json
- pnpm-lock.yaml
> Revert "fix(deps): update dependency framer-motion to v11.0.12"

- packages/@1/modules/opportunity/api/src/index.ts
> feat(api): set opportunity order

- package.json
This reverts commit 273aa2ce038820a5f4ae1e89d464c80bf957d9c1.
> Revert "chore(deps): update node.js to v20.13.0 (#1204)"

- apps/www/app/(home)/ConnectionPanel.tsx
- apps/www/components/navbar/aside_navbar.tsx
- packages/@1/modules/forum/ui/src/CreateCard/Idle.tsx
- packages/@1/ui/react/src/error/index.tsx
> fix(app):grammar errors

- packages/@1/modules/exchange/api/src/me/find.ts
> fix(exchange):  display first exchange without deal

- apps/www/app/(main)/opportunities/_client/List.tsx
- packages/@1/modules/opportunity/api/src/find.ts
> feat(opportunities): search on locations too

- apps/www/app/(main)/opportunities/_client/SearchForm.tsx
> ux(app): search felt laggy

- apps/www/app/(main)/exchanges/_client/SearchForm.tsx
- packages/@1/modules/exchange/api/src/index.ts
- packages/@1/modules/exchange/api/src/me/find.ts
fixes #1211 
We should open a new issue because insensitiveness isn't working for some reason.
Also, we should talk about the placeholder as I think this might be a source of useless work to wrote "Recherche par mot clé ou par ville" instead of "Recherche". We may replace "Recherche" by "Ex: Mot clé, ville" . This is shorter so may be easier for responsive design.
Let me know.
I also add locations onto the exchange thread part.
This is a really long PR. Love
> feat(exchanges): search on locations too

- apps/www/app/(main)/exchanges/_client/SearchForm.tsx
- apps/www/app/(main)/opportunities/_client/SearchForm.tsx
- apps/www/app/constants.tsx
> refacto(app):spell to summon magic numbers 🧙‍♂️

- apps/www/widgets/exchanges/card/ask.tsx
> fix(exchange): ask modal disapear before final message

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/_client/Infinite_Thread_Timeline.tsx
- packages/@1/infra/database/prisma/seed.ts
- packages/@1/modules/exchange/api/src/me/action.ts
- packages/@1/modules/exchange/domain/src/deal.machine.ts
- packages/@1/modules/exchange/domain/src/is_exchange_completed.ts
> feat(exhange): broadcast when every participant are accepted

- packages/@1/modules/exchange/ui/src/OnlineOrLocation.tsx
> feat(exchange):location linked to search on location

- package.json
- turbo.json
> chore(turbo): do not cache studio task

- turbo.json
> chore(turbo): do not cache apps dev task

- CONTRIBUTING.md
- README.md
- app.json
- apps/www/app/(auth)/layout.tsx
- apps/www/app/(home)/page.client.tsx
- apps/www/app/layout.tsx
- apps/www/app/not-found.tsx
- apps/www/components/placeholder/TocToc_Placeholder.tsx
- apps/www/components/shell/Footer.tsx
- apps/www/components/shell/TocTocLogo.tsx
- packages/@1/modules/auth/emails/emails/magic-link.tsx
> feat(www): change the website name to serkels

- apps/www/app/(home)/LoginForm.tsx
- apps/www/next.config.mjs
> chore(home): disable the partner button

- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.client.tsx
- apps/www/components/InfoBox.tsx
- apps/www/widgets/exchanges/card/index.tsx
- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
> feat(exchanges): disable edition when it has participants

- apps/www/app/(main)/(about)/who/page.tsx
Closes https://github.com/toctocorg/toctoc/issues/1323
> feat(www): update who page

- packages/@1/modules/exchange/api/src/index.ts
- packages/@1/modules/exchange/ui/src/Card/Date.tsx
> feat(exchange): do not display expired exchanges

- packages/@1/infra/database/prisma/seed.ts
- packages/@1/modules/exchange/api/src/index.ts
> feat(exchange): ensure to display unactive exchanges

- packages/@1/modules/inbox/ui/src/thread/Thread_Item.tsx
> feat(inbox): change date format

- apps/www/app/(main)/door/[code]/(public)/(about)/page.tsx
> feat(www): remove university on the about

- packages/@1/modules/exchange/api/src/me/find.ts
Reverts toctocorg/toctoc#1225
---
We will be using advance filters for this
> Revert "fix(exchange):  display first exchange without deal"

- apps/www/components/navbar/aside_navbar.tsx
> feat(www): rename studient exchanges links

- packages/@1/modules/exchange/api/src/me/find.ts
> feat(exchange): remove completed exchanges from user list

- package.json
- pnpm-lock.yaml
> chore(lock): ensure the same next version

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/Infinite_Exchange_List.tsx
- packages/@1/modules/exchange/ui/src/Card/Date.tsx
> feat(exchange): use expired date as date in the inbox list

- packages/@1/modules/exchange/ui/src/Card/Card_Deleting.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
> feat(exchange): rename seats to participants

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/Infinite_Exchange_List.tsx
> feat(exchange): remove dispo word

- packages/@1/modules/exchange/ui/src/Card/exchange_card.tsx
> fix(responsive): flex-row into info bar

- packages/@1/modules/exchange/api/src/index.ts
- packages/@1/modules/exchange/api/src/me/index.ts
- packages/@1/modules/exchange/domain/src/index.ts
> fix(exchanges): zod accept undefined

- packages/@1/modules/exchange/api/src/index.ts
> fix(exchange): ensure to liste flexible exchanges

- apps/www/app/(main)/door/[code]/(private)/exchanges/mine/page.tsx
- packages/@1/modules/exchange/api/src/index.ts
- packages/@1/modules/exchange/api/src/me/index.ts
</p>
---
Fixes https://github.com/toctocorg/toctoc/issues/1403
> fix(studient): empty my publication page

- packages/@1/modules/exchange/ui/src/Card/Date.tsx
> fix(exchange): missing limite date label next to the date in the card

- apps/www/app/(main)/door/[code]/(private)/exchanges/new/page.client.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Deleting.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
- packages/@1/modules/exchange/ui/src/ask/form.tsx
- packages/@1/modules/opportunity/domain/src/index.ts
- packages/@1/modules/opportunity/ui/src/Card.tsx
> fix(titles): opportunities and exchange's title are now limited to 100 ch

- packages/@1/modules/exchange/ui/src/Card/Date.tsx
> fix(exchange): put expired dates in danger

- apps/www/widgets/exchanges/card/actions.tsx
- packages/@1/modules/exchange/ui/src/ask/form.tsx
</p>
---
Closes https://github.com/toctocorg/toctoc/issues/1265
> feat(exchange): change ask modal placeholder

- packages/@douglasduteil/config/tailwindcss/prettier.config.mjs
> chore(prettier): tailwindPreserveWhitespace

- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/_client/Infinite_Thread_List.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx
- packages/@1/modules/inbox/api/src/index.ts
- packages/@1/modules/inbox/api/src/thread.ts
> fix(inbox): the message is read when you look at it

- packages/@1/infra/database/prisma/seed.ts
> chore(database): add official Ahmad Ali University VIP partner

- apps/www/app/(main)/(about)/faq/page.tsx
- apps/www/app/(main)/(about)/legal/page.tsx
- apps/www/app/(main)/(about)/who/page.tsx
> feat(about): add more space on mobile

- apps/www/sentry.client.config.ts
- apps/www/sentry.edge.config.ts
- apps/www/sentry.server.config.ts
> chore(app): desable sentry in dev

- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/_client/Infinite_Thread_List.tsx
> fix(app): resolve confusing key and id

- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
- packages/@1/ui/react/src/form/atom.ts
> fix(responsive): exchange form is user friendly on mobile

- apps/www/app/(home)/page.client.tsx
> fix(www): carousel aligned with the connection panel

- apps/www/widgets/exchanges/card/index.tsx
> fix(exchange): can't edit because wrong logic

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/@navbar/default.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/default.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/write_to/_client/Infinite_Contacts_List.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/write_to/page.tsx
- apps/www/components/button/BackButton.tsx
- apps/www/public/back.svg
- packages/@1/ui/react/src/avatar/atom.ts
> feat(navigation): back buttons are here. To improve regarding placement

- packages/@1/infra/database/prisma/seed.ts
> chore(database): add official Juliet Meere University VIP partner

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/Infinite_Exchange_List.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/@navbar/default.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/_client/Infinite_Thread_List.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/layout.tsx
- apps/www/app/(main)/door/[code]/layout.tsx
- packages/@1/modules/exchange/api/src/me/find.ts
- packages/@1/modules/exchange/ui/src/aside/InfiniteList.tsx
- packages/@1/ui/react/src/grid/atom.ts
> fix(app): some reponsive bugs

- packages/@1/ui/react/src/avatar/atom.ts
> fix(ui): avoid avatar squeeze

- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/_client/Conversation_Form.tsx
- apps/www/package.json
- pnpm-lock.yaml
> fix(www): only use enter to send message on desktop

- apps/www/app/(main)/door/[code]/(public)/@header/default.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/AddContact.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/default.client.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/menu.tsx
- apps/www/app/(main)/door/[code]/(public)/layout.tsx
- packages/@1/ui/react/src/menu/atom.ts
- packages/@1/ui/react/src/menu/index.tsx
</p>
---
Closes https://github.com/toctocorg/toctoc/issues/1226
> feat(app): add contextual menu

- apps/www/widgets/exchanges/card/index.tsx
- packages/@1/modules/exchange/ui/package.json
- packages/@1/modules/exchange/ui/src/Card/Card.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
- pnpm-lock.yaml
Closes https://github.com/toctocorg/toctoc/issues/1212
> feat(exchange): add description to be markdown

- packages/@1/ui/react/src/avatar/atom.ts
<p align =center>${\color{lightgreen}FIXES}$ #1545 </p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXVkemp6bTgwYWYwcnk0ZTd3bnV4Y3hzd3Q0cG01YXlvYWhicmNhMSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4ogaN4QJMTy8NoEtDO/giphy.gif"></p>
> fix(home): PP is now OP

- packages/@1/modules/category/ui/src/form/SelectCategoryField.tsx
- packages/@1/modules/forum/ui/package.json
- packages/@1/modules/forum/ui/src/Answer/Form.tsx
- packages/@1/modules/forum/ui/src/CreateCard/Form.tsx
- packages/@1/ui/react/package.json
- packages/@1/ui/react/src/form/atom.ts
- pnpm-lock.yaml
> refacto(forum): use react-hook-form

- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/AddContact.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/default.client.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/menu.tsx
- packages/@1/ui/react/src/menu/atom.ts
- packages/@1/ui/react/src/menu/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDIxNjFoZGVsc25ta3JoZmJ3eHFnaTMwcW12b2ljcmx2c2gxYXRzNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4o88fi5sw9Vx0tzYQx/giphy.gif"></p>
fixes #1517
> fix(profile): menu and navbar fix

- apps/www/components/navbar/aside_navbar.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/7opnzydyXGEembl6nm/giphy.gif?cid=ecf05e47punefbu0563pqmesac334xu33awx30xxck584yff&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
fixes #1561
> feat(inbox):renaming

- apps/www/app/(main)/door/[code]/(public)/contacts/page.tsx
- packages/@1/ui/react/src/async/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXl5azNpa2NwdzA5Y2VobDg2MzB3ZHEyYnE4MGpjeThyM3VxNDF1diZlcD12MV9naWZzX3NlYXJjaCZjdD1n/gLcsg9oLmrpDBYK2Qb/giphy.gif"></p>
<p align=center>Can i find a more perfect gif for that ? I DON'T THINK SO !</p>
fixes #1510
> feat(inbox): confusing empty inbox

- packages/@1/infra/database/prisma/seed.ts
1st iteration.
<p align =center>${\color{Dandelion}CONCERN}$ #1515 </p><p align=center><img src="https://media.giphy.com/media/HRIReXsB4BU5JbsQ7k/giphy.gif?cid=ecf05e479k61j51iwlfck3lofzadmig0qzqqf7hdatbhy1tw&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> feat(categories): rename activity to not break the design 

- apps/www/app/(main)/exchanges/layout.tsx
- apps/www/app/(main)/forum/layout.tsx
- apps/www/app/(main)/forum/page.tsx
- apps/www/app/(main)/opportunities/layout.tsx
- apps/www/components/shell/AsideFilter.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/JaETEIF9XYJE7d5om1/giphy.gif?cid=790b7611eh58l2293uemooz2w8xavnae4lpwlo91fzt5tpzw&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
fixes #1563 
fixes #1564 
fixes #1565
> feat(subtitle): add subtitles to pages

- apps/www/app/(auth)/signup/student/page.tsx
- apps/www/app/(main)/door/[code]/(private)/parameters/_client/Student_Editor.tsx
- apps/www/app/(main)/door/[code]/(private)/parameters/page.tsx
- packages/@1/modules/category/ui/src/form/SelectCategoryField.tsx
- packages/@1/modules/profile/api/src/student.ts
> feat(profile): add interest fied to profile parameter

- apps/www/app/(main)/forum/_client/List.tsx
- packages/@1/modules/forum/ui/src/Answer/Card.tsx
- packages/@1/modules/forum/ui/src/QuestionCard/Card.tsx
- packages/@1/modules/forum/ui/src/QuestionCard/Header.tsx
<div align="center">
</div>
Closes #1509
> fix(forum): make profile avatar a link

- apps/www/app/(home)/page.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.client.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/Follow.tsx
- apps/www/app/(main)/exchanges/_client/Exchanges_Filter.tsx
- apps/www/app/(main)/exchanges/_client/List.tsx
- apps/www/app/(main)/exchanges/layout.tsx
- apps/www/app/(main)/exchanges/page.tsx
- apps/www/components/shell/MobileNavBar.tsx
- apps/www/widgets/exchanges/card/actions.tsx
- apps/www/widgets/exchanges/card/bookmark.tsx
- apps/www/widgets/exchanges/card/index.tsx
- apps/www/widgets/exchanges/card/login.tsx
- packages/@1/modules/exchange/api/src/find.ts
- packages/@1/modules/exchange/api/src/index.ts
- packages/@1/modules/exchange/ui/src/Card/context.tsx
<div align="center">
</div>
Closes #1408
> feat(exchange): exchange are now public

- packages/@1/infra/database/prisma/seed.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHR0dmpmZml4MGFxNHY0ZTF3eWJ1dTYyeXpoN2x2ZjQzYTE0aGFnZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/yrFrXTTTcHIY0/giphy.gif"></p>
fixes #1581
> feat(opportunities):remove activities

- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.client.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/new/page.client.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/new/page.tsx
- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
- packages/@1/ui/react/src/form/atom.ts
> feat(exchange): use react-hook-form

- apps/www/app/(main)/forum/page.tsx
> fix(forum): group create form and answer message

- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExanBwaDdpM3l2OXM3Yjk5cHlkOHBwcmdteTZkdWFiN3Izdm56Nzd3aCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o6nVa6P4VpvBMHSso/giphy.gif"></p><p align =right>fix #1674 </p>
> fix(form):translate error message to french

- apps/www/app/(auth)/signup/partner/page.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/default.client.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXFnNjk5dm56dWJ0eWdwODA5Z3NmNWJtd3U1aGxrbjh2NDN6dG01MiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/26uffpkCkNgQGx5dK/giphy.gif"></p>
<p align =right>fix #1673</p>
> bug(profile): partener navbar

- apps/www/widgets/exchanges/card/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3h5dDdiaWl5ZjF3MW9iZmh2MTd1MWFkOWtqN3J4bnkyYnk3YXM1ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/CaaQxoAktdZCbDSLqJ/giphy.gif"></p>
<p align =right>fixes #1699</p>
> fix(exchange):description take all the width

- apps/www/app/(main)/door/[code]/(public)/@navbar/menu.tsx
- apps/www/app/(main)/door/[code]/report/action.ts
- apps/www/app/(main)/door/[code]/report/page.client.tsx
- apps/www/app/(main)/opportunities/_client/Item.tsx
- apps/www/widgets/exchanges/card/bookmark.tsx
- packages/@1/modules/profile/domain/src/report.ts
Also fix spelling mistakes linked to reporting and form validation
<p align =center>${\color{orange}FEAT}$ AND ${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/3o6Ztq7p5irM9yPFmw/giphy.gif?cid=790b7611uig52onoz881a8y6yy0tgwhws8ii1ffuxqwjjpto&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
> feat(toast): toast when a report is submit + spelling mistake 

- apps/www/app/(main)/door/[code]/(private)/bookmarks/exchanges/page.tsx
- apps/www/app/(main)/door/[code]/(private)/bookmarks/layout.tsx
- apps/www/app/(main)/door/[code]/(private)/bookmarks/opportunities/page.tsx
- apps/www/app/(main)/door/[code]/(public)/history/page.tsx
- apps/www/app/(main)/door/[code]/(public)/opportunities/page.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWIwNmc3YnlxMzdkb2RmdGFxaWI4eHBhMGZ1MGFnM3VtYXc2YWhyNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/26hkhPJ5hmdD87HYA/giphy.gif"></p><p align =right>fix #1675</p>
> fix(profile): translate empty pages

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/_client/Infinite_Thread_Timeline.tsx
- packages/@1/modules/exchange/domain/src/handshake_format.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGZraHN0Njl2bDJ1ajZlY2U4NHlpNDhxMjNxamlzczlrYW5zbW9wNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Qw1acdtxOfrFDd2uti/giphy.gif"></p><p align =right>fix #1678 </p>
> feat(exchange): change refused exchange message

- apps/e2e/features/studient/about.feature
- apps/e2e/features/studient/contacts.feature
- apps/e2e/features/studient/following.feature
- apps/www/app/(auth)/confirm/[token]/authorized/page.tsx
- apps/www/app/(auth)/signup/(state)/authorized/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/default.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/write_to/page.tsx
- apps/www/app/(main)/door/[code]/(public)/@header/default.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/AddContact.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/SendMessage.tsx
- apps/www/app/(main)/door/[code]/(public)/contacts/page.tsx
- apps/www/app/(main)/door/[code]/(public)/following/page.tsx
- apps/www/components/navbar/aside_navbar.tsx
- packages/@1/ui/react/src/async/index.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/3o7aD6ydPRgEPllYQM/giphy.gif?cid=790b7611dc1v8j4xp84sr2w3mq5gs8bpdvdbji7bo5svczny&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
<p align =right>fix #1681</p>
> feat(*): change titles

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/_client/FilterForm.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/@navbar/default.tsx
- packages/@1/ui/react/src/async/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/kKdbm7emfVgYNTT2sG/giphy.gif?cid=790b7611guvj0iq6f539papqaf5yk4bmue7w5x3f0lwprki9&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1695 </p>
> feat(exchange): emphase on the filter button

- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
- packages/@1/ui/react/src/form/atom.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/pcLl99vJzXvESh6unI/giphy.gif?cid=790b76112t5x2kcm8tp5w6lqtablxt19yru8s2rx1b3jm9fx&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p>
<p align=center>THIS IS A RADIO CHECK !</p><p align =right>fix #1708 </p>
> bug(exchange): change Contre un échange radio

- apps/e2e/features/forum/public.feature
- apps/www/app/(home)/page.tsx
- apps/www/app/(main)/forum/layout.tsx
- apps/www/app/(main)/forum/page.tsx
- apps/www/components/shell/MobileNavBar.tsx
- packages/@1/modules/forum/ui/src/CreateCard/Form.tsx
- packages/@1/ui/react/src/form/atom.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/W2iXEVritYvPXq3k1N/giphy.gif?cid=790b76118vw81knt69wog6rue3zikzuwcac1htefelazm8aq&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1679 </p>
> feat(forum): change forum title

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/_client/Infinite_Thread_Timeline.tsx
- packages/@1/modules/inbox/ui/src/thread/Thread_Item.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/hWGhxXRWSgIWAYKzOA/giphy.gif?cid=790b7611xun7ww8suy8hmlag8gf17izq8uuvzo1bq2rbzfs7&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1680 </p>
> fix(time):remove time from Date on inbox

- packages/@1/infra/database/prisma/seed.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/OOF1pWIRZ9mIAyDl3h/giphy.gif?cid=790b7611d90lvxvmeqbyulgll63jfo40ytx7ov0unmechrwp&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1682 </p>
> feat(categories) :welcome to objects

- .github/workflows/e2e.yaml
- apps/e2e/features/exchanges/single.feature
- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.client.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/new/page.client.tsx
- apps/www/app/(main)/exchanges/@categories/Filter.tsx
- apps/www/app/(main)/exchanges/@see_also/default.tsx
- apps/www/app/(main)/exchanges/[exchange_id]/Card.tsx
- apps/www/app/(main)/exchanges/[exchange_id]/layout.tsx
- apps/www/app/(main)/exchanges/[exchange_id]/not-found.tsx
- apps/www/app/(main)/exchanges/[exchange_id]/page.tsx
- apps/www/app/(main)/exchanges/_client/Exchanges_Filter.tsx
- apps/www/widgets/exchanges/card/share.tsx
- packages/@1/infra/database/prisma/seed.ts
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
> feat(exchange): add single exchange route

- packages/@1/ui/react/src/icons/Messenger.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcjJqaWtxanY5NWJiYnptbml0bTFrZmI2ZDZkMzM3NmM3bHB3Y250cSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/M2l4lBm8B1iHvDl7jX/giphy.gif"></p><p align =right>fix #1693 </p>
> feat(inbox): change inbox icon

- apps/www/app/(main)/door/[code]/(public)/contacts/_client/Infinite_Contacts_List.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNXhvYms3dDA1Z2gzOWc2cTVzMnE4bWNjeTZzZjFsODBnZHNlbXJsNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/NVBR6cLvUjV9C/giphy.gif"></p><p align =right>fix #1702 </p>
> bug(profile): contact list item should link to user profiles

- apps/www/app/(main)/forum/_client/List.tsx
- packages/@1/modules/forum/api/src/answers.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/W0SLa0YuzWBZ6/giphy.gif?cid=790b7611rhgg9qyb71fv3iuc2umpzv3oajo3dhp5leysvcwa&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1441 </p>
> feat(forum): add disapprove button to answer

- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/6S05PmFz8Bwo1vp6AE/giphy.gif?cid=790b76118k7pg9ckcsow59xf1ah0ttols4g8s8eewcvhixcy&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1677 </p>
> feat(exchange): add warning before creation

- apps/www/app/(main)/forum/_client/List.tsx
- packages/@1/modules/forum/api/package.json
- packages/@1/modules/forum/api/src/answers.ts
- packages/@1/modules/forum/api/src/question.ts
- packages/@1/modules/forum/ui/src/Answer/Card.tsx
- packages/@1/modules/forum/ui/src/QuestionCard/Header.tsx
- pnpm-lock.yaml
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/ATt7p8OO4mvvO/giphy.gif?cid=790b7611ptc5v0j0ry9207234ax5w4qnelx7oq7906arvr3s&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1706</p>
> feat(forum): delete my question and my answer

- apps/www/app/(main)/door/[code]/(private)/exchanges/[exchange_id]/edit/page.client.tsx
- packages/@1/modules/exchange/ui/src/form/new_exchange.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/10xp3IDPPOG1OM/giphy.gif?cid=790b7611njlhwxujw4kygf7mznwtj0apg0da5ryg7qwx38oa&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1708 </p>
> feat(exchange):display placeholder

- apps/www/widgets/exchanges/card/bookmark.tsx
- apps/www/widgets/exchanges/card/delete.button.tsx
- apps/www/widgets/exchanges/card/index.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/BTtkhBLbMUD16/giphy.gif?cid=790b7611sfip6mfrafp9tgdg5f1g812dr8rq6v0gkcqld9yt&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1697 and fix #1744 </p>
> feat(exchange): move action button to the bottom of the card

- packages/@1/modules/exchange/api/src/find.ts
- packages/@1/modules/exchange/api/src/index.ts
> fix(exchange): order by expiry date first

- packages/@1/infra/database/prisma/seed.ts
- packages/@1/modules/exchange/api/src/find.ts
> bug(exchange): hide completed exchange from the public list

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/_client/Conversation_Form.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
- packages/@1/modules/exchange/api/src/me/inbox.ts
- packages/@1/modules/exchange/domain/src/index.ts
- packages/@1/modules/inbox/ui/src/conversation/Conversation.tsx
- packages/@1/modules/inbox/ui/src/conversation/MessageForm.tsx
- packages/@1/ui/react/src/form/SendButton.tsx
> feat(exchange): should not be able to send message to a participant/owner of a expired exchange

- apps/www/app/(main)/door/[code]/(private)/notifications/List.tsx
- packages/@1/infra/database/prisma/migrations/20240913152643_add_profile_added_notification/migration.sql
- packages/@1/infra/database/prisma/schema.prisma
- packages/@1/infra/database/prisma/seed.ts
- packages/@1/modules/core/src/date.ts
- packages/@1/modules/notification/api/src/find.ts
- packages/@1/modules/notification/domain/package.json
- packages/@1/modules/notification/domain/src/Notification.ts
- packages/@1/modules/notification/domain/src/ProfileNotification.ts
- packages/@1/modules/notification/domain/src/index.ts
- packages/@1/modules/notification/ui/package.json
- packages/@1/modules/notification/ui/src/DotIndicator.tsx
- packages/@1/modules/notification/ui/src/card/ProfileAdded.tsx
- packages/@1/modules/notification/ui/src/card/atom.ts
- packages/@1/modules/profile/api/src/me.ts
- packages/@1/modules/profile/api/src/me/toggle/index.ts
- pnpm-lock.yaml
> feat(notification): notify user of new contact

- apps/www/widgets/exchanges/card/login.tsx
- packages/@1/modules/exchange/ui/src/ask/modal.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/f9k1tV7HyORcngKF8v/giphy.gif?cid=790b7611qjyt0ysdi2hzaifc2kxjg3j1sh31d16alxow076i&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1696</p>
> fix(exchange): popup when not connected

- apps/www/app/(main)/door/[code]/(private)/notifications/List.tsx
- apps/www/components/button/MarkAsRead.tsx
- packages/@1/modules/notification/ui/src/card/ProfileAdded.tsx
\following https://github.com/Serkels/serkels.eu/issues/1439 #1780
> feat(notification): marck add profile as read

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/_client/Conversation_Form.tsx
- apps/www/app/(main)/door/[code]/(private)/inbox/[thread_id]/page.tsx
- apps/www/app/(main)/door/[code]/(public)/(about)/page.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/BlockProfile.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/default.client.tsx
- apps/www/app/(main)/exchanges/_client/List.tsx
- apps/www/components/placeholder/BlockedProfile_Placeholder.tsx
- apps/www/widgets/inbox/BlockedProfileWarning.tsx
- packages/@1/infra/database/prisma/migrations/20240914030436_add_profile_blacklist/migration.sql
- packages/@1/infra/database/prisma/schema.prisma
- packages/@1/modules/exchange/api/src/find.ts
- packages/@1/modules/inbox/api/package.json
- packages/@1/modules/inbox/api/src/_send.ts
- packages/@1/modules/inbox/api/src/find/index.ts
- packages/@1/modules/inbox/api/src/index.ts
- packages/@1/modules/inbox/api/src/send/index.ts
- packages/@1/modules/inbox/api/src/thread.ts
- packages/@1/modules/inbox/api/src/thread/messages/index.ts
- packages/@1/modules/inbox/domain/src/select.ts
- packages/@1/modules/profile/api/src/me.ts
- packages/@1/modules/profile/api/src/me/blacklist/index.ts
- packages/@1/modules/trpc/src/index.ts
\linked to [#1710](https://github.com/Serkels/serkels.eu/issues/1710)
> feat: block a profile

- apps/www/app/(main)/forum/_client/List.tsx
- apps/www/app/(main)/forum/page.tsx
- packages/@1/infra/database/seeding/category/film.ts
- packages/@1/infra/database/seeding/index.ts
- packages/@1/modules/exchange/api/src/public/__snapshots__/find.e2e.test.ts.snap
- packages/@1/modules/exchange/api/src/public/by_id.e2e.test.ts
- packages/@1/modules/exchange/api/src/public/by_id.ts
- packages/@1/modules/exchange/api/src/public/find.e2e.test.ts
- packages/@1/modules/exchange/api/src/public/find.ts
- packages/@1/modules/forum/api/src/question.ts
- packages/@1/modules/forum/api/src/question/find/__snapshots__/index.e2e.test.ts.snap
- packages/@1/modules/forum/api/src/question/find/index.e2e.test.ts
- packages/@1/modules/forum/api/src/question/find/index.ts
- packages/@1/modules/profile/ui/src/BlockedInfoMessage.tsx
- packages/@1/modules/trpc/src/index.ts
> feat(forum): hide blocked questions

- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/@navbar/_client/menu.tsx
- apps/www/app/(main)/door/[code]/(private)/exchanges/inbox/[exchange_id]/@navbar/default.tsx
- packages/@1/infra/database/prisma/migrations/20240915171915_add_is_archived_exchange_for_studient/migration.sql
- packages/@1/infra/database/prisma/schema.prisma
- packages/@1/modules/exchange/api/src/me/__snapshots__/find.e2e.test.ts.snap
- packages/@1/modules/exchange/api/src/me/archive/index.ts
- packages/@1/modules/exchange/api/src/me/find.e2e.test.ts
- packages/@1/modules/exchange/api/src/me/find.ts
- packages/@1/modules/exchange/api/src/me/index.ts
- packages/@1/modules/exchange/ui/src/aside/TitleHeader.tsx
- packages/@1/ui/react/src/menu/index.tsx
> feat(exchange): archive an exchange

- packages/@1/infra/database/prisma/seed.ts
- packages/@1/infra/database/seeding/exchange/the_creator.ts
- packages/@1/infra/database/seeding/index.ts
- packages/@1/modules/exchange/api/src/me/__snapshots__/find.e2e.test.ts.snap
- packages/@1/modules/exchange/api/src/me/action.ts
- packages/@1/modules/exchange/api/src/me/find.e2e.test.ts
- packages/@1/modules/exchange/api/src/me/find.ts
> feat(exchange): auto remove from list after participant denied action

- apps/www/app/(home)/layout.tsx
- apps/www/app/(main)/navbar.tsx
- apps/www/components/burger/index.tsx
- apps/www/components/shell/AppSidebar.tsx
> feat(www): move main layout menu burger

- apps/www/components/navbar/aside_navbar.client.tsx
- apps/www/components/navbar/aside_navbar.tsx
> feat(www): reorder studient aside navbar

- apps/e2e/features/studient/inbox.feature
- apps/www/app/(main)/door/[code]/(private)/inbox/@navbar/default.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/1ULD8e5wLnTIm0VGUj/giphy.gif?cid=790b7611r7wyzg8pviuzpmmqpdks73awqafblzwf6sg83l2t&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1765</p>
> fix(inbox): multiline button cropping

- apps/www/app/(main)/door/[code]/(public)/history/page.tsx
- apps/www/app/(main)/door/[code]/(public)/proposals/page.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/7BNUFlsGtI3quyeUn3/giphy.gif?cid=790b761121s725ft4pqdt5apmx8fkse04ij1youmzrqx8gr8&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1813</p>
> fix(exchange): Exchange editing issue

- apps/www/app/(main)/door/[code]/report/page.client.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/1ZDM388Wrje4uS5zGj/giphy.gif?cid=790b7611248hikoxgq6t9p9bo6ef8n1it6pqg2uze083u4nn&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1711</p>
> fix(toast): weird count was cuz weird dev

- apps/www/app/(main)/door/[code]/(private)/notifications/ExchangeNewParticipant.tsx
- apps/www/app/(main)/door/[code]/(private)/notifications/ForumNewAnswer.tsx
- apps/www/app/(main)/door/[code]/(private)/notifications/InboxNewMessage.tsx
- apps/www/app/(main)/door/[code]/(private)/notifications/List.tsx
- packages/@1/modules/notification/api/src/find.ts
- packages/@1/modules/notification/domain/src/ExchangeNotification.ts
- packages/@1/modules/notification/ui/src/card/ExchangeCompletedMessage.tsx
- packages/@1/modules/notification/ui/src/card/ExchangeNewMessage.tsx
- packages/@1/modules/notification/ui/src/card/ProfileAdded.tsx
- packages/@1/modules/notification/ui/src/card/atom.ts
- packages/@1/ui/react/src/card/atom.ts
<p align =center>${\color{lightgreen}FIX}$ and ${\color{orange}FEAT}$  </p></p><p align=center><img src="https://media.giphy.com/media/ckxEuxmbsdbs84HxvP/giphy.gif?cid=ecf05e47ark13kxt5x0ohv1bjudlqxwbymhlgavubcra7oxf&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1784 and #1785 </p>
> feat(notifications):rework on notifications display

- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/AddContact.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/_client/SendMessage.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/default.client.tsx
- apps/www/app/(main)/door/[code]/(public)/@navbar/menu.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExenlkNTUyNHR3bHFudjZwcjB5cG5sODFhdjRlYWM2c2NlMHZnaDF2cSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/PckENlUnKcb4fXk5gn/giphy.gif"></p><p align =right>fix #1715 and fix #1703</p>
> feat(profile): move Envoyer un message privé to dropdown

- apps/www/components/Share_Button.tsx
- apps/www/widgets/exchanges/card/delete.button.tsx
- apps/www/widgets/exchanges/card/index.tsx
- apps/www/widgets/exchanges/card/share.tsx
- packages/@1/modules/exchange/ui/src/Card/Card_Idle.tsx
- packages/@1/modules/profile/ui/src/avatar.tsx
- packages/@1/ui/react/src/button/atom.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/LMQ9c65BnD2gzMiJWg/giphy.gif?cid=ecf05e470rxybwn265mc1qpdl54ht0ysg20xsu9es63ijnot&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1767</p>
> fix(exchanges): Edit buttons are wild

- apps/www/.env
- apps/www/.env.development
Following [#1877](https://github.com/Serkels/serkels.eu/issues/1877)
> fix(auth): only use localhost on development env

- apps/e2e/features/auth/signup.feature
- apps/www/app/(home)/LoginForm.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/t0virGpgSlp4mkfiXq/giphy.gif?cid=790b76117a5q6j0rbmzrd19xse8bkttqulxrher52auopody&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1683 </p>
> feat(auth): change connexion panel layout

- apps/www/widgets/opportunities/card/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2Yxc2p4Zjh3czRuanRlaXBxMnBid3diOTV6dmgyM3pnN3cxeWtpciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/SV03XkNPDE28NISRGw/giphy.gif"></p><p align=center >BISTOU ! Stay put little button</p><p align =right>fix #1893</p>
> fix(opportunities): bookmark buttons were wild

- apps/www/app/(main)/opportunities/[slug]/page.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/lOrQ4RM66Hyqky5st2/giphy.gif?cid=ecf05e47llknbm0tenst8bf0vrb726t065fyugtyyazzrica&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1872 </p>
> bug(ui): weird avatar

- apps/www/app/(home)/ConnectionPanel.tsx
- packages/@1/infra/trpc/src/auth.ts
- packages/@1/infra/trpc/src/index.ts
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/5xaOcLyjXRo4hX5UhSU/giphy.gif?cid=790b7611gyutxif9ckden7go5ar756h3gry9kr94w0jl01i2&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1914</p>
> feat(auth): do not allow profile to login if the user is not found

- apps/www/app/(main)/forum/_client/List.tsx
- packages/@1/modules/forum/ui/src/QuestionCard/ResponseButtons.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/tvLwCpHvWFnhrcsUfI/giphy.gif?cid=790b7611544zxyqng1iu19htde0on8q7w831eeh3imnk4uen&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1934 </p>
> feat(partner): cannot respond to questions in discussions

- packages/@1/ui/react/src/avatar/atom.ts
> fix(ui): weird avatar

- packages/@1/modules/opportunity/ui/src/Article.tsx
> fix(opportunity): max ratio

- apps/www/app/(main)/door/[code]/(public)/@header/AddedByCount.tsx
- apps/www/app/(main)/door/[code]/(public)/@header/CircleCount.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/26BoDYDTteuyZCh3y/giphy.gif?cid=790b7611xism4daszs311jfirmx3c9ws7p2v6dtywu43nt36&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #1916 </p>
> feat(profile): add some color to the counts

- apps/www/app/(main)/(about)/moderation/content.md
- apps/www/app/(main)/(about)/moderation/page.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/13fpglQTVROjT2/giphy.gif?cid=790b76116467ow88a54ag158sx6c2u872lavzabaqpupnyra&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2000 </p>
> feat(moderation):add moderation page from commit 3ee72ae

- apps/www/app/(main)/(about)/notices/content.md
- apps/www/app/(main)/(about)/notices/page.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/sLVLojotxREBy/giphy.gif?cid=790b761127leeytdq6d0jy8zqtjcfqyky34kxk4x6vend64d&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2003 </p>
> feat(notices):add legal notices page

- apps/www/app/(main)/(about)/who/content.md
- apps/www/app/(main)/(about)/who/page.tsx
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/H7JD0pfyksePe/giphy.gif?cid=790b7611e86mtsd44kdpi4f24ha3g98n2pt58cuv9psbwczp&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2005 </p>
> feat(who):update who are we page and title

- apps/www/app/(main)/(about)/who/content.md
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/zsg9Adj13Dh2E/giphy.gif?cid=790b7611vc7wwinqm38tpgghnn00li9rx32afjqla9wyxw5z&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2009 </p>
> fix(who): sillat was too soon

- apps/www/app/(main)/(about)/faq/content.md
- apps/www/app/(main)/(about)/faq/page.tsx
- apps/www/package.json
- pnpm-lock.yaml
<p align =center>${\color{orange}FEAT}$ </p></p><p align=center><img src="https://media.giphy.com/media/TgF6xfH8V0mZcUyneP/giphy.gif?cid=790b7611n27bcs103sriq2mhl2pr8en15pkuegp71myi23fq&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2007 </p>
> feat(faq): add real faq to the website

- apps/www/app/(main)/navbar.tsx
> fix(www): stacked user button on desktop

- packages/@douglasduteil/nextauth...trpc.prisma/package.json
- pnpm-lock.yaml
Reverts Serkels/serkels.eu#2142
> Revert "fix(deps): update dependency next-auth to v4.24.11"

- apps/www/app/(main)/layout.tsx
- apps/www/components/shell/Footer.tsx
- packages/@1/ui/react/src/grid/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXM3djY4ZWNzNmZlaTYzeG1raWdpN2s3eXZhMndsdGY1NjR4NnlrdyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/S3iA49EWhmNhAcj8YJ/giphy.gif"></p><p align =right>fix #2183 </p>
> fix(www): multi line footer links

- apps/www/components/shell/Footer.tsx
- packages/@1/ui/react/src/grid/index.tsx
<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/purpeEw5dYmiLfEfON/giphy.gif?cid=790b7611tcwv4xzmsywnmi7amhtjfw3ibpu8dga5ins70ume&ep=v1_gifs_search&rid=giphy.gif&ct=g"></p><p align =right>fix #2188 </p>
> fix(www): mb was my bad

- apps/e2e/package.json
- pnpm-lock.yaml
Reverts Serkels/serkels.eu#2181
> Revert "fix(deps): update dependency cypress to v14"
